name: Voice Instruments
author: WeMake
markdown: kramdown
baseurl:
permalink: blog/:year/:month/:day/:title/
plugins:
  - jekyll-sitemap
  # - jekyll-paginate
# paginate: 10
# paginate_path: /blog/page:num/
exclude: [README.md]
github: [metadata]

title: "Voice Instruments by opencarecc"
tagline: "This is the Voice Instruments' websites"

# multilingual stuff
index:
  en:
  it: it/index.html

default_lang: "en"
